name: test

on:
  pull_request:
  push:
    branches:
      - "!gh-pages"
      - "**"
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-latest", "windows-latest"]
        python: ["3.5", "3.6", "3.7"]
    name: ${{ matrix.os }} ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run test
        run: |
          CVR_DEV_LIVE_TESTS=true python -m unittest
        env:
          CVR_DEV_TEST_API_KEY: ${{ secrets.CVR_DEV_TEST_API_KEY }}

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
